---
EnableDefaultLinters: true
linters:
    ErbSafety:
        enabled: true
    Rubocop:
        enabled: true
        rubocop_config:
            inherit_gem:
                standard: config/base.yml
            inherit_from:
                - .rubocop.yml
