###########################
# Configuration for rubocop
# in .rubocop.yml
# Most of these are disabling existing cops, primarily
# due to a smattering of different styles and loose
# guidelines for contributions.
#
# Any of these may be changed.
require:
  - standard
  - rubocop-rails
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-performance

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - "node_modules/**/*"
    - "public/**/*"
    - "vendor/**/*"

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops

# * Disable cops here
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
Style/StringLiterals:
  EnforcedStyle: double_quotes
RSpec/NestedGroups:
  Max: 5
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
