# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: Testing the application

on:
    push:
        branches: ["pre-production"]
    pull_request:
        branches: ["pre-production"]

jobs:
    rspec-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name:
                  Setup PostgreSQL with PostgreSQL extensions and unprivileged user
                  # You may pin to the exact commit or the version.
                  # uses: Daniel-Marynicz/postgresql-action@79215751c10f38d037032a85feebba06c1c13968
              uses: Daniel-Marynicz/postgresql-action@1.0.0
              # with:
              #   # Docker postgres image tag for available image tags please see https://hub.docker.com/_/postgres
              #   postgres_image_tag: # optional, default is latest
              #   # Docker postgres image name if not using https://hub.docker.com/_/postgres
              #   postgres_image_name: # optional, default is postgres
              #   # POSTGRES_USER - create the user with the superuser power
              #   postgres_user: # optional, default is postgres
              #   # POSTGRES_DB - postgres database
              #   postgres_db: # optional, default is postgres
              #   # POSTGRES_PASSWORD - superuser password
              #   postgres_password: # optional
              #   # POSTGRES_EXTENSIONS - List of postgres extensions separated by space to install in template1 database
              #   postgres_extensions: # optional
              #   # APP_USER - unprivileged postgres user
              #   app_user: # optional, default is app
              #   # APP_PASSWORD_USER - password for unprivileged postgres user
              #   app_user_password: # optional, default is app
              #   # APP_DB - database or list of databases separated by space for unprivileged postgres user
              #   app_db: # optional, default is app
              #   # EXPOSED_POSTGRES_PORT - exposed postgres port
              #   exposed_postgres_port: # optional, default is 5432

            - name: Setup Ruby
              uses: ruby/setup-ruby@v1.138.0
              with:
                  ruby-version: 3.1.2

            - name: Install Dependencies
              run: gem install bundler

            - name: Install Gems
              run: bundle install

            - name: Prepare Database
              env:
                  DATABASE_URL: postgres://app:app@localhost:5432/fmb_test
              run: bundle exec rails db:setup

            - name: Run routing tests
              env:
                  DATABASE_URL: postgres://app:app@localhost:5432/fmb_test
              run: rspec spec/routing -fd
